### PR TITLE
Updated StateKitLite.cs

### PR DESCRIPTION
**Pull request by djfdat**
Removed unused namespaces, variables, and code.

### CODE REVIEW

**Comment by prime31** [comment]
You can take away elapsedTimeInState and previousState! I use those all the time! I did just push a change with the unused using statements though. That I'll allow ;)

**Comment by djfdat** [comment]
It doesn't look like they're being used in StateKitLite, but they are having values assigned to them. Should be safe to get rid of, since I don't think anything else is using StateKitLite, although I haven't checked the other classes.

**Comment by prime31** [comment]
They arent used in StateKitLite but they are protected fields so that subclasses can access them. StateKitLite is just one class that is meant to be subclassed. They are super handy to have in your subclasses (I use them all the time personally).

**Comment by djfdat** [comment]
Now that you mention it, previousState would actually be good for something I'm doing. Totally forgot about that use case!

**Pull request closed without merging**
